
#include <stdio.h>
#ifndef INVENTORYMANAGER_INTERCALACAOBASICAADAPTADA_H
#define INVENTORYMANAGER_INTERCALACAOBASICAADAPTADA_H
FILE* intercalacaoBasicaAdaptada(FILE **files, int num_p, char fileName[]);
#endif //INVENTORYMANAGER_INTERCALACAOBASICAADAPTADA_H
